Algoritmo "Retângulo"
Var
     y: inteiro
     x: inteiro
     area: inteiro

Inicio
      escreval("Programa que cálcula a área de um retângulo com dois números inteiros.")
      escreval("")
      escreva("Digite o valor da altura do retângulo:")
      leia(x)
      escreval("")
      escreva("Digite o valor do comprimento do retângulo")
      leia(y)
      escreval("")
      area <- x*y
      escreva("O valor da área do retângulo é:", area,"cm²")
Fimalgoritmo