Algoritmo "Subtração"

Var
  numero01: inteiro
  numero02: inteiro
  subtracao: inteiro
Inicio
  Escreval("Este programa faz a subtração de dois números inteiros.")
  Escreval("")
  Escreva ("Digite o primeiro valor inteiro:")
  Leia (numero01)
  Escreval("")
  Escreva ("Digite o segundo valor inteiro:")
  Leia (numero02)
  subtracao <- numero01 - numero02
  Escreval("")
  Escreva ("O valor da subtração é:", subtracao)
Fimalgoritmo